version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-chat-app
    environment:
      MONGO_INITDB_DATABASE: chat-app
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
